### ISSUE TITLE
Fails to get deps that don't end with version numbers

### ISSUE THREAD

**Issue by isabelroses** [nekowinston/nix-deno#11]
When trying to get [@bcherny/json-schema-ref-parser](https://www.npmjs.com/package/@bcherny/json-schema-ref-parser) it queries
> https://registry.npmjs.org/@bcherny/json-schema-ref-parser/-/json-schema-ref-parser-10.0.5.tgz

when it should be

> https://registry.npmjs.org/@bcherny/json-schema-ref-parser/-/json-schema-ref-parser-10.0.5-fork.tgz

**Comment by nekowinston** [comment]
Could you please try with `github:nekowinston/nix-deno/fix/npm-semver-dash` and report back if that fixes it? Seems to work fine locally.

**Comment by isabelroses** [comment]
Seem to work for me now, thanks for being so fast.

**Comment by nekowinston** [comment]
Interesting side note: it occurred to me that a simple `-suffix` isn't enough for packages like `tailwindcss@insiders`, and when I cached it, I found a `tailwindcss@0.0.0-insiders.f1f419a_postcss@8.4.38` in my `deno.lock`. 👀 

Luckily it turns out that `package.json` `version` **must be** parsable by `npm:semver`:
![2024-04-24-224008@2x](https://github.com/nekowinston/nix-deno/assets/79978224/c9b45aaa-f75a-49ad-ab73-fb1c0bc73156)

So the correct POSIX regex seems to be `(^@?[[:alnum:]/._-]+)@([[:alnum:].-]+).*` in the end.
